import json

D = {
"rucksack": "This is a key bit of equipment, especially during trek when you'll carry 15-25kg of group kit. Look for: top-loading (a side-loading 'travel pack' won't support your back properly), 65-85 litre capacity depending on your body size, an adjustable back length, and comfortable, padded straps. This needs to fit ALL your kit inside it, so it's worth investing in a good one rather than borrowing an old or ill-fitting bag.",
"daybag": "Essential for carrying sunscreen, water bottle etc. to the project site each day, and doubles as your hand luggage on flights. An old school/college bag is fine - no need to buy new.",
"sleepingbag": "Choose a synthetic bag (down bags are harder to dry and deteriorate in humid conditions). Comfort rating should suit the destination's temperature range - ask us if unsure. You'll be sleeping in this most nights of the expedition.",
"sleepingbagliner": "Keeps your sleeping bag clean and is far easier to wash. A cheap DIY option: fold a cotton sheet in half lengthways and stitch the long sides together, or use an old single duvet cover.",
"sleepingmat": "Full-length mats are best - remember you'll be sleeping on this for weeks. Foam mats are cheap (under GBP5); self-inflating mats are comfier but pricier and can puncture (bring a repair kit if so).",
"drybags": "Waterproof bags you pack inside your rucksack to keep kit dry. Bring 2-3 in a mix of sizes - one small (camera/notepad), one larger (sleeping bag/clothes change). A rucksack liner is an alternative and should match your rucksack's capacity.",
"watercontainers": "Bring a mix of hard bottles and collapsible containers to carry at least 3 litres. Collapsible containers pack down small when empty. You'll always be asked to drink purified water on expedition (1 puritab = 1 litre).",
"headtorch": "Essential as there's rarely electricity on project sites - keeps your hands free. Bring at least one set of spare batteries. LED bulbs use less power, and a red-light setting attracts fewer insects at night. Worth packing a cheap backup hand torch too.",
"messtin": "A square metal container with a handle, used as a bowl for eating on placement. Available from camping shops, or bring a metal plate/bowl from home.",
"mug": "For hot drinks (tea, coffee etc). An old mug from home is fine - a small thermos/flask also works well.",
"cutlery": "Bring a knife, fork and spoon - a set from home is fine. Camping 'sporks' can be flimsy and may need replacing.",
"sunglasses": "It's likely to be bright and sunny - make sure lenses have effective UV protection. A hard case is worth bringing.",
"prescriptionglasses": "Bring a spare pair if possible, both in hard cases. Contact lenses are not permitted due to higher infection risk in a dirtier environment.",
"toiletrieswash": "Hygiene is crucial on expedition. Bring the essentials, with opportunities to restock certain items (e.g. toothpaste) during changeovers.",
"towel": "Lightweight, compact, quick-drying travel towels are recommended over a normal cotton towel. A sarong is a popular lightweight alternative that doubles as a blanket.",
"watch": "There will be a lot of early mornings, so a watch with an alarm is recommended - a cheap plastic one is fine. Look for a light and water resistance.",
"documents": "Keep copies of your passport photo page, vaccination dates, bank/card emergency contacts, insurance policy and emergency contact number, and a spare flight e-ticket, separate from the originals in case anything is lost or stolen.",
"puritabs": "Each group is given purification droplets/tablets for large quantities of water, but you need your own small personal supply for emergencies. Cheap chlorine-based puritabs can be bought online.",
"firstaidkitgeneral": "You must bring your own personal first aid kit - buy a pre-made kit and add any missing items, or assemble the items individually and store in a wash bag.",
"string": "Useful for improvising washing lines and hanging mosquito nets. Paracord is more hardwearing and reusable than standard string. No more than 15m is needed.",
"sewingkit": "Useful for repairing kit and clothing throughout the expedition. A cheap non-branded kit is fine.",
"padlock": "Useful for securing kit while travelling and in storage. If transiting through the USA, make sure it's TSA-approved or it may be broken during customs searches.",
"penknife": "Handy for general use - an inexpensive multi-tool with a blade under 2 inches, can opener and scissors is ideal. Must go in hold luggage, not hand luggage.",
"holdall": "A lightweight cover bag that protects your rucksack's straps during flights and can be padlocked for extra security. Make sure its capacity is bigger than your rucksack. Can be left at Field Base during trek.",
"money": "Raleigh covers your in-country travel, accommodation and food. Bring some spending money for extras like souvenirs, snacks and toiletries - see the detailed guidance for recommended amounts, which vary by expedition length.",
"camera": "As phones aren't allowed on project, a camera is a great way to capture the expedition. Avoid expensive/bulky items like tablets or laptops as we can't securely store high-value items. Bring spare batteries and enough memory cards, plus a waterproof case.",
"mosquitonet": "Reduces the risk of insect-borne illness while sleeping. A box-shaped net is easiest to put up since it attaches at all four corners. It must be pre-treated with permethrin - buy a treatment bottle separately if using an old/untreated net.",
"trekkingpoles": "A matter of personal preference - some Venturers find these help on steep or uneven ground. A sturdy stick picked up locally works just as well.",
"cards": "Great for filling downtime in the evenings and bonding with the team.",
"journal": "Useful for notes during training and project planning, and for keeping entertained when there's no phone signal. Bring writing paper so you can write home too.",
"sparelaces": "Useful backup in case your boot laces break mid-expedition. Take up almost no space.",
"pillow": "A small luxury - a dry bag stuffed with clothes or your fleece works just as well if you'd rather save the space.",
"gaffatape": "Useful for repairing almost anything - tents, bags, kit. A non-branded roll saves money.",
"bungee": "Elasticated cords with hooks, useful for securing equipment and rigging shelters. One or two is plenty.",
"handwarmers": "Reusable handwarmers help on cold nights and mornings during the cooler cycle. Bring reusable ones (rather than single-use) to last the whole cycle and reduce waste.",
"soap": "Basic hygiene essential - try to bring biodegradable or eco-friendly options where possible.",
"shampoo": "Shampoo/conditioner bars take up minimal space and are more eco-friendly than bottles - available from stores like LUSH or Holland & Barrett.",
"toothbrush": "Standard hygiene essential for the whole expedition.",
"toothpaste": "You can usually restock this during changeovers in town if you run low.",
"deodorant": "Choose unscented or low-fragrance options where possible, as strong scents can attract insects.",
"insectrepellent": "Look for a strong DEET concentration - this can be expensive or hard to find in-country, so bring enough for the full expedition.",
"sunscreen": "Minimum SPF30 (or SPF50 in tropical climates) - sunscreen can be pricey to buy locally, so pack enough to last, especially for the trek phase.",
"laundrywash": "An eco-friendly wash bar or gel lets you hand-wash clothes on project without harming local water sources.",
"oralrehydration": "Sachets like Dioralyte help you rehydrate quickly if you're unwell in the heat or after a stomach bug.",
"painrelief": "Standard paracetamol/ibuprofen for headaches, muscle aches and minor pain.",
"blisterplasters": "Specialist plasters that cushion and protect blisters, particularly important during the trek phase when you'll be walking long distances daily.",
"zincoxide": "Tape used to protect feet from blisters (often applied before trek) and for general strapping/repairs.",
"footpowder": "Helps keep feet dry to prevent fungal infections like athlete's foot, especially useful in hot, humid conditions.",
"plasters": "Standard plasters for minor cuts and grazes.",
"antisepticspray": "For cleaning cuts and grazes to prevent infection before dressing them.",
"handsanitiser": "Important for hygiene where handwashing facilities may be limited on project sites.",
"antihistaminetablets": "For allergic reactions and insect bites/stings.",
"antihistaminecream": "A topical cream to relieve itching and irritation from insect bites.",
"prescriptionmeds": "Bring enough for the full expedition plus extra time in case of travel delays or lost/damaged medication. Let the Expedition Team know in advance if you're taking prescription medication.",
"scissors": "Small first aid scissors for cutting tape, plasters or clothing in an emergency.",
"tweezers": "Useful for removing splinters, thorns or ticks.",
"bandage": "A conforming bandage for securing dressings or supporting minor sprains.",
"vaseline": "Useful for chafing, dry lips and minor skin protection - a small tin is enough.",
"boots": "A key investment alongside your rucksack - make sure boots are comfortable, offer ankle support, and are broken in with several short walks (up to 5 miles) before you arrive. Avoid Timberland/Caterpillar-style work boots as they're not suitable for hiking.",
"sandals": "Must have toe and ankle straps to stay on your feet and dry out easily - used for washing and river crossings. Crocs with a closed toe are a good choice in jungle environments to keep insects off your feet.",
"longsleeve": "Worn at dusk and dawn to protect against mosquitoes, and during the day for sun protection. Lightweight, quick-dry fabric is ideal.",
"tshirts": "Must cover the shoulders and dry quickly - old, cheap tops work just as well as expensive brands.",
"fleece": "Temperatures drop at night and in the mornings, especially at altitude or in the jungle - fleece dries faster than a thick hoody and is also useful for travel days.",
"warmjacket": "An extra warm layer needed only for the cooler cycle - pack this in addition to your fleece if travelling during that period.",
"thermals": "A base layer for cold nights and mornings during the cooler cycle - not required for warmer cycles.",
"trousers": "Bring at least one pair suited to trekking (quick-dry hiking trousers) and a lighter pair for relaxing at Field Base. Avoid jeans on project - they're too hot and slow to dry. Zip-off trousers that convert to shorts save packing space.",
"shorts": "Must reach the knee for cultural sensitivity on community projects - quick-dry sports shorts with cargo pockets are ideal.",
"socks": "Bring a mix of walking socks (for trek and long days on your feet) and normal cotton socks (cooler, for evenings).",
"underwear": "Bring enough to last the expedition, plus a spare set to leave at Field Base. Dark colours hide dirt better.",
"bras": "Sports bras are generally found to be more comfortable for active days.",
"workgloves": "Hard-wearing gloves for manual work on project sites - available cheaply from hardware stores or supermarkets.",
"hat": "A wide brim protects your face and neck from sun and rain.",
"waterproofjacket": "A lightweight waterproof jacket or poncho for wet weather - jackets are more practical, ponchos cover more of your kit but restrict movement.",
"swimwear": "Needed for washing in rivers/streams as well as any swimming. Board shorts or a costume with a T-shirt over the top may be more culturally appropriate on projects.",
"buff": "A versatile piece of neck/head wear useful for sun and dust protection.",
"warmhat": "A warm hat for cold mornings and evenings during the cooler cycle.",
"gloves": "Warm gloves useful for cold mornings and evenings.",
"othershoes": "Comfortable alternatives to boots/sandals for relaxing at Field Base, e.g. trainers or flip flops.",
"nicerclothes": "Worth having one clean, presentable outfit for changeovers, community events, and travel days.",
}

def item(name, qty, cat, sub, cycle="all", desc_key=None, desc_text=None):
    return {
        "item": name,
        "quantity": qty,
        "category": cat,
        "subcategory": sub,
        "cycle": cycle,
        "description": desc_text if desc_text else D.get(desc_key, "Recommended by the Raleigh Expedition Team as part of the standard kit list for this destination.")
    }

# ---------------- SOUTH AFRICA ----------------
south_africa = [
    item("Rucksack (65-85 Litres)", "1", "essential", "personal", desc_key="rucksack"),
    item("Day bag", "1", "essential", "personal", desc_key="daybag"),
    item("Sleeping bag (2-3 seasons)", "1", "essential", "personal", desc_key="sleepingbag"),
    item("Sleeping bag liner", "1", "essential", "personal", desc_key="sleepingbagliner"),
    item("Roll / sleeping mat", "1", "essential", "personal", desc_key="sleepingmat"),
    item("Dry bags & rucksack liner", "2-3", "essential", "personal", desc_key="drybags"),
    item("Water containers", "2-3 (3 litres min)", "essential", "personal", desc_key="watercontainers"),
    item("Head torch + spare batteries", "1", "essential", "personal", desc_key="headtorch"),
    item("Mess tin / bowl", "1", "essential", "personal", desc_key="messtin"),
    item("Mug", "1", "essential", "personal", desc_key="mug"),
    item("Cutlery (knife/fork/spoon)", "1 set", "essential", "personal", desc_key="cutlery"),
    item("Sunglasses", "1", "essential", "personal", desc_key="sunglasses"),
    item("Prescription glasses", "1 (plus spare)", "essential", "personal", desc_key="prescriptionglasses"),
    item("Toiletries & wash stuff", "1 set", "essential", "personal", desc_key="toiletrieswash"),
    item("Towel", "1", "essential", "personal", desc_key="towel"),
    item("Watch with an alarm", "1", "essential", "personal", desc_key="watch"),
    item("Photocopies of key documents", "1 set", "essential", "personal", desc_key="documents"),
    item("Water purification tablets", "10", "essential", "personal", desc_key="puritabs"),
    item("First aid kit", "1", "essential", "personal", desc_key="firstaidkitgeneral"),

    item("String / paracord", "10-15m", "recommended", "personal", desc_key="string"),
    item("Sewing kit", "1", "recommended", "personal", desc_key="sewingkit"),
    item("Padlock", "1", "recommended", "personal", desc_key="padlock"),
    item("Pen knife or multi-tool", "1 (blade under 2 inches)", "recommended", "personal", desc_key="penknife"),
    item("Travel holdall / rucksack cover bag", "1", "recommended", "personal", desc_key="holdall"),
    item("Money", "See spending guidance", "recommended", "personal", desc_key="money"),
    item("Camera", "1", "recommended", "personal", desc_key="camera"),

    item("Mosquito net", "1", "optional", "personal", desc_key="mosquitonet"),
    item("Trekking poles", "1", "optional", "personal", desc_key="trekkingpoles"),
    item("Playing cards / games", "1", "optional", "personal", desc_key="cards"),
    item("Journal / pen / pencil / paper", "1 set", "optional", "personal", desc_key="journal"),
    item("Spare laces", "1", "optional", "personal", desc_key="sparelaces"),
    item("Inflatable pillow", "1", "optional", "personal", desc_key="pillow"),
    item("Gaffa / duct tape", "1 roll", "optional", "personal", desc_key="gaffatape"),
    item("Bungee cords", "2", "optional", "personal", desc_key="bungee"),
    item("Reusable handwarmers", "2", "optional", "personal", cycle=2, desc_key="handwarmers"),

    item("Soap", "1", "essential", "toiletries", desc_key="soap"),
    item("Shampoo / conditioner", "1", "essential", "toiletries", desc_key="shampoo"),
    item("Toothbrush", "1", "essential", "toiletries", desc_key="toothbrush"),
    item("Toothpaste", "1", "essential", "toiletries", desc_key="toothpaste"),
    item("Deodorant", "1", "essential", "toiletries", desc_key="deodorant"),
    item("Insect repellent", "1", "essential", "toiletries", desc_key="insectrepellent"),
    item("Sunscreen / sunblock (min. 30 SPF)", "1 x 200ml", "essential", "toiletries", desc_key="sunscreen"),
    item("Eco-friendly laundry wash bar / gel", "1", "essential", "toiletries", desc_key="laundrywash"),

    item("Oral rehydration sachets", "30", "essential", "firstaid", desc_key="oralrehydration"),
    item("Pain relief tablets (paracetamol/ibuprofen)", "2 packets each (max 32 tablets)", "essential", "firstaid", desc_key="painrelief"),
    item("Blister plasters", "Min 10 large", "essential", "firstaid", desc_key="blisterplasters"),
    item("Zinc oxide tape (min 5cm wide)", "1-2 rolls", "essential", "firstaid", desc_key="zincoxide"),
    item("Anti-fungal foot powder", "20-50ml/g", "essential", "firstaid", desc_key="footpowder"),
    item("Plasters", "1 packet", "essential", "firstaid", desc_key="plasters"),
    item("Antiseptic spray / cream", "50-100ml or 1 tube", "essential", "firstaid", desc_key="antisepticspray"),
    item("Hand sanitiser / gel", "250ml bottle", "essential", "firstaid", desc_key="handsanitiser"),
    item("Antihistamine tablets", "1 pack", "essential", "firstaid", desc_key="antihistaminetablets"),
    item("Antihistamine or hydrocortisone 1% cream", "1 tube", "essential", "firstaid", desc_key="antihistaminecream"),
    item("Prescription medication / EpiPens", "Enough for expedition + 2 weeks", "essential", "firstaid", desc_key="prescriptionmeds"),

    item("Scissors", "1", "recommended", "firstaid", desc_key="scissors"),
    item("Tweezers", "1", "recommended", "firstaid", desc_key="tweezers"),
    item("Conforming bandage (100mm)", "2", "recommended", "firstaid", desc_key="bandage"),
    item("Vaseline", "1 small tin (20g)", "recommended", "firstaid", desc_key="vaseline"),

    item("Walking boots (broken in)", "1", "essential", "clothing", desc_key="boots"),
    item("Sandals (toe and ankle straps)", "1", "essential", "clothing", desc_key="sandals"),
    item("Long sleeved tops / shirts", "1-2 (Cycle 2 needs 2)", "essential", "clothing", desc_key="longsleeve"),
    item("T-shirts", "3-4", "essential", "clothing", desc_key="tshirts"),
    item("Fleece / jumper", "1-2 (Cycle 2 needs 2)", "essential", "clothing", desc_key="fleece"),
    item("Warm jacket", "1", "essential", "clothing", cycle=2, desc_key="warmjacket"),
    item("Thermal leggings & top", "1 set", "essential", "clothing", cycle=2, desc_key="thermals"),
    item("Trousers", "2", "essential", "clothing", desc_key="trousers"),
    item("Shorts", "2-3", "essential", "clothing", desc_key="shorts"),
    item("Socks (walking + normal)", "3-4x walking, 4x normal", "essential", "clothing", desc_key="socks"),
    item("Underwear", "4-7", "essential", "clothing", desc_key="underwear"),
    item("Bras", "2-3", "essential", "clothing", desc_key="bras"),
    item("Hat (wide brimmed)", "1", "essential", "clothing", desc_key="hat"),
    item("Lightweight waterproof jacket", "1", "essential", "clothing", desc_key="waterproofjacket"),
    item("Swimming costume / bikini", "1", "essential", "clothing", desc_key="swimwear"),
    item("Buff", "1", "essential", "clothing", desc_key="buff"),
    item("Warm hat", "1", "essential", "clothing", cycle=2, desc_key="warmhat"),
    item("Gloves", "1", "essential", "clothing", cycle=2, desc_key="gloves"),

    item("Other shoes (trainers / flip flops)", "1", "recommended", "clothing", desc_key="othershoes"),
    item("Set of clothes for field base / travelling", "1-2", "recommended", "clothing", desc_key="nicerclothes"),
    item("Work / garden gloves", "1", "recommended", "clothing", desc_key="workgloves"),
]

# ---------------- COSTA RICA ----------------
costa_rica = [
    item("Rucksack (65-85 Litres)", "1", "essential", "personal", desc_key="rucksack"),
    item("Day bag", "1", "essential", "personal", desc_key="daybag"),
    item("Sleeping bag (2-3 seasons)", "1", "essential", "personal", desc_key="sleepingbag"),
    item("Sleeping bag liner", "1", "essential", "personal", desc_key="sleepingbagliner"),
    item("Roll / sleeping mat", "1", "essential", "personal", desc_key="sleepingmat"),
    item("Dry bags & rucksack liner", "2-3", "essential", "personal", desc_key="drybags"),
    item("Water containers", "2-3 (3 litres min)", "essential", "personal", desc_key="watercontainers"),
    item("Head torch", "1", "essential", "personal", desc_key="headtorch"),
    item("Mess tin / plate / bowl", "1", "essential", "personal", desc_key="messtin"),
    item("Mug", "1", "essential", "personal", desc_key="mug"),
    item("Cutlery", "1 set", "essential", "personal", desc_key="cutlery"),
    item("Sunglasses", "1", "essential", "personal", desc_key="sunglasses"),
    item("First aid kit", "1", "essential", "personal", desc_key="firstaidkitgeneral"),
    item("Toiletries & hygiene items", "1 set", "essential", "personal", desc_key="toiletrieswash"),
    item("Towel", "1", "essential", "personal", desc_key="towel"),
    item("Photocopies of key documents", "1 set", "essential", "personal", desc_key="documents"),
    item("Water purification tablets", "30 tablets", "essential", "personal", desc_key="puritabs"),
    item("Gaffa / duct tape", "1 roll", "essential", "personal", desc_key="gaffatape"),
    item("Mosquito net", "1", "essential", "personal", desc_key="mosquitonet"),
    item("Money", "See spending guidance", "essential", "personal", desc_key="money"),

    item("String / paracord", "10-15m", "recommended", "personal", desc_key="string"),
    item("Sewing kit", "1", "recommended", "personal", desc_key="sewingkit"),
    item("Padlocks", "1", "recommended", "personal", desc_key="padlock"),
    item("Pen knife or multi-tool", "1 (blade under 2 inches)", "recommended", "personal", desc_key="penknife"),
    item("Bungee cords", "2", "recommended", "personal", desc_key="bungee"),
    item("Watch with an alarm", "1", "recommended", "personal", desc_key="watch"),
    item("Travel holdall / rucksack cover bag", "1", "recommended", "personal", desc_key="holdall"),
    item("Small travel camera", "1", "recommended", "personal", desc_key="camera"),
    item("Trekking poles", "1 pair", "recommended", "personal", desc_key="trekkingpoles"),

    item("Playing cards / games", "1", "optional", "personal", desc_key="cards"),
    item("Journal / pen / pencil / paper", "1 set", "optional", "personal", desc_key="journal"),
    item("Spanish phrase book", "1", "optional", "personal", desc_text="A little Spanish goes a long way when working closely with Costa Rican teammates and local communities. Duolingo or a phrasebook before you go is invaluable."),
    item("Travel-proof holdall", "1", "optional", "personal", desc_key="holdall"),

    item("Liquid body wash / hand soap", "1", "essential", "toiletries", desc_key="soap"),
    item("Bar of soap", "1", "essential", "toiletries", desc_key="soap"),
    item("Shampoo / conditioner", "1", "essential", "toiletries", desc_key="shampoo"),

    item("Oral rehydration sachets", "4 packs of 20", "essential", "firstaid", desc_key="oralrehydration"),
    item("Pain relief tablets (paracetamol/ibuprofen)", "4 packets of each", "essential", "firstaid", desc_key="painrelief"),
    item("Blister plasters", "Min 5 large", "essential", "firstaid", desc_key="blisterplasters"),
    item("Zinc oxide tape (min 5cm wide)", "2-4 rolls", "essential", "firstaid", desc_key="zincoxide"),
    item("Anti-fungal foot powder / talcum powder", "1-2 pots 20-50ml/g", "essential", "firstaid", desc_key="footpowder"),
    item("Plasters", "1 packet", "essential", "firstaid", desc_key="plasters"),
    item("Antiseptic solution", "50-100ml", "essential", "firstaid", desc_key="antisepticspray"),
    item("Antiseptic spray / cream", "1 tube", "essential", "firstaid", desc_key="antisepticspray"),
    item("Hand sanitiser / gel", "250ml bottle", "essential", "firstaid", desc_key="handsanitiser"),
    item("Insect repellent (50% DEET)", "1 large + 1 small bottle", "essential", "firstaid", desc_key="insectrepellent"),
    item("Sunscreen / sunblock (min. 30 SPF)", "1 large + 1 small bottle", "essential", "firstaid", desc_key="sunscreen"),
    item("Prescription medication", "Enough for expedition + 2 weeks", "essential", "firstaid", desc_key="prescriptionmeds"),
    item("Scissors", "1", "essential", "firstaid", desc_key="scissors"),
    item("Tweezers", "1", "essential", "firstaid", desc_key="tweezers"),
    item("Antihistamine or hydrocortisone 1% cream", "1 tube", "essential", "firstaid", desc_key="antihistaminecream"),
    item("Antihistamine tablets", "4 packs", "essential", "firstaid", desc_key="antihistaminetablets"),
    item("Vaseline", "1 pot", "essential", "firstaid", desc_key="vaseline"),

    item("Walking boots", "1", "essential", "clothing", desc_key="boots"),
    item("Spare laces", "1", "essential", "clothing", desc_key="sparelaces"),
    item("Sandals", "1", "essential", "clothing", desc_key="sandals"),
    item("Long sleeved tops", "2", "essential", "clothing", desc_key="longsleeve"),
    item("T-shirts", "3-4", "essential", "clothing", desc_key="tshirts"),
    item("Fleece", "1", "essential", "clothing", desc_key="fleece"),
    item("Warm jacket", "1", "essential", "clothing", desc_key="warmjacket"),
    item("Trousers", "2", "essential", "clothing", desc_key="trousers"),
    item("Shorts", "2", "essential", "clothing", desc_key="shorts"),
    item("Socks (walking + normal)", "4x walking, 4x normal", "essential", "clothing", desc_key="socks"),
    item("Underwear", "6-8", "essential", "clothing", desc_key="underwear"),
    item("Work / garden gloves", "1", "essential", "clothing", desc_key="workgloves"),
    item("Hat (wide brimmed)", "1", "essential", "clothing", desc_key="hat"),
    item("Lightweight waterproof jacket", "1", "essential", "clothing", desc_key="waterproofjacket"),
    item("Swimming costume", "1", "essential", "clothing", desc_key="swimwear"),
    item("Flip flops", "1", "essential", "clothing", desc_key="othershoes"),

    item("Other shoes (e.g. trainers)", "1", "recommended", "clothing", desc_key="othershoes"),
    item("Nicer set of clothes for Fieldbase / travelling", "1", "recommended", "clothing", desc_key="nicerclothes"),
    item("Beanie hat", "1", "recommended", "clothing", cycle=3, desc_key="warmhat"),
    item("Gloves", "1", "recommended", "clothing", cycle=3, desc_key="gloves"),
]

# ---------------- BORNEO ----------------
borneo = [
    item("Rucksack (65-85 Litres)", "1", "essential", "personal", desc_key="rucksack"),
    item("Day bag (30 litres)", "1", "essential", "personal", desc_key="daybag"),
    item("Sleeping bag (1-2 seasons)", "1", "essential", "personal", desc_key="sleepingbag"),
    item("Sleeping bag liner", "1", "essential", "personal", desc_key="sleepingbagliner"),
    item("Roll / sleeping mat", "1", "essential", "personal", desc_key="sleepingmat"),
    item("Mosquito net (box shaped)", "1", "essential", "personal", desc_key="mosquitonet"),
    item("String / paracord", "10-15m", "essential", "personal", desc_key="string"),
    item("Dry bags & rucksack liner", "2-3", "essential", "personal", desc_key="drybags"),
    item("Water containers (wide brimmed)", "3 (1 litre each)", "essential", "personal", desc_key="watercontainers"),
    item("Head torch + spare batteries", "1", "essential", "personal", desc_key="headtorch"),
    item("Mess tin / travel bowl", "1", "essential", "personal", desc_key="messtin"),
    item("Mug", "1", "essential", "personal", desc_key="mug"),
    item("Cutlery (K/F/S)", "1 set", "essential", "personal", desc_key="cutlery"),
    item("Sunglasses", "1", "essential", "personal", desc_key="sunglasses"),
    item("Prescription glasses", "1 (plus spare)", "essential", "personal", desc_key="prescriptionglasses"),
    item("Toiletries & wash stuff", "1 set", "essential", "personal", desc_key="toiletrieswash"),
    item("Quick dry towel", "1", "essential", "personal", desc_key="towel"),
    item("Watch with an alarm", "1", "essential", "personal", desc_key="watch"),
    item("Photocopies of key documents", "1 set", "essential", "personal", desc_key="documents"),
    item("First aid kit", "1", "essential", "personal", desc_key="firstaidkitgeneral"),
    item("Money", "See spending guidance", "essential", "personal", desc_key="money"),

    item("Sewing kit", "1", "recommended", "personal", desc_key="sewingkit"),
    item("Padlock", "1", "recommended", "personal", desc_key="padlock"),
    item("Pen knife or multi-tool", "1 (blade under 2 inches)", "recommended", "personal", desc_key="penknife"),
    item("Travel holdall / rucksack cover bag", "1", "recommended", "personal", desc_key="holdall"),
    item("Camera", "1", "recommended", "personal", desc_key="camera"),
    item("Gaffa / duct tape", "1 roll", "recommended", "personal", desc_key="gaffatape"),
    item("Bungee cords", "2", "recommended", "personal", desc_key="bungee"),

    item("Trekking poles", "1", "optional", "personal", desc_key="trekkingpoles"),
    item("Playing cards / games", "1", "optional", "personal", desc_key="cards"),
    item("Journal / pen / pencil / paper", "1 set", "optional", "personal", desc_key="journal"),
    item("Spare laces", "1", "optional", "personal", desc_key="sparelaces"),
    item("Inflatable pillow", "1", "optional", "personal", desc_key="pillow"),
    item("Umbrella", "1", "optional", "personal", desc_text="Handy in Borneo's heavy rain, particularly around Field Base. Not practical to use on trek."),

    item("Soap", "1", "essential", "toiletries", desc_key="soap"),
    item("Shampoo / conditioner", "1", "essential", "toiletries", desc_key="shampoo"),
    item("Toothbrush", "1", "essential", "toiletries", desc_key="toothbrush"),
    item("Toothpaste", "1", "essential", "toiletries", desc_key="toothpaste"),
    item("Deodorant", "1", "essential", "toiletries", desc_key="deodorant"),
    item("Insect repellent", "2 x 200ml", "essential", "toiletries", desc_key="insectrepellent"),
    item("Sunscreen / sunblock (min. 50 SPF)", "2 x 200ml", "essential", "toiletries", desc_key="sunscreen"),
    item("Eco-friendly laundry wash bar / gel", "1-2", "essential", "toiletries", desc_key="laundrywash"),
    item("Wet wipes (biodegradable)", "1 packet min", "essential", "toiletries", desc_text="Handy for a quick clean when there's no opportunity to wash - must be biodegradable to avoid harming the local environment."),

    item("Oral rehydration sachets", "30", "essential", "firstaid", desc_key="oralrehydration"),
    item("Electrolyte tablets", "50-70 (1 per day)", "essential", "firstaid", desc_text="Replace salts and minerals lost through sweating in Borneo's heat and humidity - cheap tablets from a supermarket or outdoor store are fine."),
    item("Water purification tablets (1 litre each)", "10 strips of 10 tablets", "essential", "firstaid", desc_key="puritabs"),
    item("Pain relief tablets (paracetamol/ibuprofen)", "2 packets each (max 32 tablets)", "essential", "firstaid", desc_key="painrelief"),
    item("Loperamide (e.g. Imodium)", "1 packet", "essential", "firstaid", desc_text="For managing an upset stomach - useful during trek when access to a toilet is limited."),
    item("Blister plasters", "Min 10 large", "essential", "firstaid", desc_key="blisterplasters"),
    item("Zinc oxide tape (min 5cm wide)", "1-2 rolls", "essential", "firstaid", desc_key="zincoxide"),
    item("Anti-fungal foot powder", "20-50ml/g", "essential", "firstaid", desc_key="footpowder"),
    item("Plasters", "1 packet", "essential", "firstaid", desc_key="plasters"),
    item("Antiseptic spray", "50-100ml or 1 tube", "essential", "firstaid", desc_key="antisepticspray"),
    item("Antiseptic wipes", "10-20", "essential", "firstaid", desc_key="antisepticspray"),
    item("Hand sanitiser / gel", "250ml bottle", "essential", "firstaid", desc_key="handsanitiser"),
    item("Antihistamine tablets", "1 pack", "essential", "firstaid", desc_key="antihistaminetablets"),
    item("Antihistamine or hydrocortisone 1% cream", "1 tube", "essential", "firstaid", desc_key="antihistaminecream"),
    item("Prescription medication / EpiPens", "Enough for expedition + 2 weeks", "essential", "firstaid", desc_key="prescriptionmeds"),

    item("Scissors", "1", "recommended", "firstaid", desc_key="scissors"),
    item("Tweezers", "1", "recommended", "firstaid", desc_key="tweezers"),
    item("Conforming bandage (100mm)", "2", "recommended", "firstaid", desc_key="bandage"),
    item("Vaseline", "1 small tin (20g)", "recommended", "firstaid", desc_key="vaseline"),

    item("Walking boots (broken in)", "1", "essential", "clothing", desc_key="boots"),
    item("Sandals or crocs (covered toe & ankle strap)", "1", "essential", "clothing", desc_key="sandals"),
    item("Lightweight long sleeved tops / shirts", "1-2", "essential", "clothing", desc_key="longsleeve"),
    item("T-shirts (quick dry)", "3-4", "essential", "clothing", desc_key="tshirts"),
    item("Fleece / jumper (for travel)", "1", "essential", "clothing", desc_key="fleece"),
    item("Trousers (quick dry)", "2 (1 hiking, 1 for chilling)", "essential", "clothing", desc_key="trousers"),
    item("Shorts (to the knee)", "2-3", "essential", "clothing", desc_key="shorts"),
    item("Socks (walking + normal)", "3-4x walking, 4x normal", "essential", "clothing", desc_key="socks"),
    item("Underwear", "4-7", "essential", "clothing", desc_key="underwear"),
    item("Bras (sports bra recommended)", "2-3", "essential", "clothing", desc_key="bras"),
    item("Work / garden gloves", "1", "essential", "clothing", desc_key="workgloves"),
    item("Hat (wide brimmed)", "1", "essential", "clothing", desc_key="hat"),
    item("Lightweight waterproof jacket", "1", "essential", "clothing", desc_key="waterproofjacket"),
    item("Swimming costume / bikini / rash vest", "1", "essential", "clothing", desc_key="swimwear"),

    item("Other shoes (trainers / flip flops / crocs)", "1", "recommended", "clothing", desc_key="othershoes"),
    item("Set of clothes for field base / travelling", "1", "recommended", "clothing", desc_key="nicerclothes"),
]

# ---------------- LEGACIES (Alumni) ----------------
legacies = [
    item("Rucksack (65-85 Litres)", "1", "essential", "personal", desc_key="rucksack"),
    item("Day bag", "1", "essential", "personal", desc_key="daybag"),
    item("Sleeping bag (2-3 seasons)", "1", "essential", "personal", desc_key="sleepingbag"),
    item("Sleeping bag liner", "1", "essential", "personal", desc_key="sleepingbagliner"),
    item("Roll / sleeping mat", "1", "essential", "personal", desc_key="sleepingmat"),
    item("Dry bags & rucksack liner", "2-3", "essential", "personal", desc_key="drybags"),
    item("Water containers", "2-3 (3 litres min)", "essential", "personal", desc_key="watercontainers"),
    item("Head torch + spare batteries", "1", "essential", "personal", desc_key="headtorch"),
    item("Mess tin / bowl", "1", "essential", "personal", desc_key="messtin"),
    item("Mug", "1", "essential", "personal", desc_key="mug"),
    item("Cutlery (K/F/S)", "1 set", "essential", "personal", desc_key="cutlery"),
    item("Sunglasses", "1", "essential", "personal", desc_key="sunglasses"),
    item("Prescription glasses", "1 (plus spare)", "essential", "personal", desc_key="prescriptionglasses"),
    item("Toiletries & wash stuff", "1 set", "essential", "personal", desc_key="toiletrieswash"),
    item("Towel", "1", "essential", "personal", desc_key="towel"),
    item("Watch with an alarm (if not taking a phone)", "1", "essential", "personal",
         desc_text="There'll be early starts, so a watch with an alarm is handy. If you're bringing a phone to use as your watch/camera, you can leave this at home."),
    item("Powerbank (20,000mAh)", "1", "essential", "personal",
         desc_text="Useful for topping up a phone or camera where charging points are limited on placement - a 20,000mAh bank will typically manage 4-5 full phone charges."),
    item("Photocopies of key documents", "1 set", "essential", "personal", desc_key="documents"),
    item("Water purification tablets", "15", "essential", "personal", desc_key="puritabs"),

    item("Pen knife or multi-tool", "1 (blade under 2 inches)", "recommended", "personal", desc_key="penknife"),
    item("Travel holdall / rucksack cover bag", "1", "recommended", "personal", desc_key="holdall"),
    item("Camera", "1", "recommended", "personal",
         desc_text="A nice way to capture memories from the trip - your phone camera works just as well if you'd rather not carry a separate device."),

    item("Mosquito net", "1", "optional", "personal", desc_key="mosquitonet"),
    item("Trekking poles", "1", "optional", "personal", desc_key="trekkingpoles"),
    item("Playing cards / games", "1", "optional", "personal", desc_key="cards"),
    item("Journal / pen / pencil / paper", "1 set", "optional", "personal", desc_key="journal"),
    item("Spare laces", "1", "optional", "personal", desc_key="sparelaces"),
    item("Inflatable pillow", "1", "optional", "personal", desc_key="pillow"),

    item("Soap", "1", "essential", "toiletries", desc_key="soap"),
    item("Shampoo / conditioner", "1", "essential", "toiletries", desc_key="shampoo"),
    item("Toothbrush", "1", "essential", "toiletries", desc_key="toothbrush"),
    item("Toothpaste", "1", "essential", "toiletries", desc_key="toothpaste"),
    item("Deodorant", "1", "essential", "toiletries", desc_key="deodorant"),
    item("Insect repellent", "1", "essential", "toiletries", desc_key="insectrepellent"),
    item("Sunscreen / sunblock (min. 30 SPF)", "1 x 200ml", "essential", "toiletries", desc_key="sunscreen"),
    item("Eco-friendly laundry wash bar / gel", "1", "essential", "toiletries", desc_key="laundrywash"),

    item("Oral rehydration sachets", "10", "essential", "firstaid", desc_key="oralrehydration"),
    item("Pain relief tablets (paracetamol/ibuprofen)", "1 packet", "essential", "firstaid", desc_key="painrelief"),
    item("Blister plasters", "Min 10 large", "essential", "firstaid", desc_key="blisterplasters"),
    item("Zinc oxide tape (min 5cm wide)", "1 roll", "essential", "firstaid", desc_key="zincoxide"),
    item("Plasters", "1 packet", "essential", "firstaid", desc_key="plasters"),
    item("Anti-fungal foot powder", "20-50ml/g", "essential", "firstaid", desc_key="footpowder"),
    item("Antiseptic spray / cream", "50-100ml or 1 tube", "essential", "firstaid", desc_key="antisepticspray"),
    item("Hand sanitiser / gel", "250ml bottle", "essential", "firstaid", desc_key="handsanitiser"),
    item("Antihistamine tablets", "1 pack", "essential", "firstaid", desc_key="antihistaminetablets"),
    item("Antihistamine or hydrocortisone 1% cream", "1 tube", "essential", "firstaid", desc_key="antihistaminecream"),
    item("Prescription medication / EpiPens", "Enough for expedition + 1 week", "essential", "firstaid", desc_key="prescriptionmeds"),

    item("Scissors", "1", "recommended", "firstaid", desc_key="scissors"),
    item("Tweezers", "1", "recommended", "firstaid", desc_key="tweezers"),
    item("Conforming bandage (100mm)", "2", "recommended", "firstaid", desc_key="bandage"),
    item("Vaseline", "1 small tub (20g)", "recommended", "firstaid", desc_key="vaseline"),

    item("Walking boots (broken in)", "1", "essential", "clothing", desc_key="boots"),
    item("Sandals (toe and ankle straps)", "1", "essential", "clothing", desc_key="sandals"),
    item("Long sleeved tops / shirts", "2", "essential", "clothing", desc_key="longsleeve"),
    item("T-shirts", "3-4", "essential", "clothing", desc_key="tshirts"),
    item("Fleece / jumper", "2", "essential", "clothing", desc_key="fleece"),
    item("Warm jacket", "1", "essential", "clothing", desc_key="warmjacket"),
    item("Thermal leggings & top", "1 set", "essential", "clothing", desc_key="thermals"),
    item("Trousers", "2", "essential", "clothing", desc_key="trousers"),
    item("Shorts", "2-3", "essential", "clothing", desc_key="shorts"),
    item("Socks (walking + normal)", "3x walking, 3-4x normal", "essential", "clothing", desc_key="socks"),
    item("Underwear", "3-4", "essential", "clothing", desc_key="underwear"),
    item("Bras", "2-3", "essential", "clothing", desc_key="bras"),
    item("Hat (wide brimmed)", "1", "essential", "clothing", desc_key="hat"),
    item("Lightweight waterproof jacket", "1", "essential", "clothing", desc_key="waterproofjacket"),
    item("Swimming costume / bikini", "1", "essential", "clothing", desc_key="swimwear"),
    item("Buff", "1", "essential", "clothing", desc_key="buff"),
    item("Warm hat", "1", "essential", "clothing", desc_key="warmhat"),
    item("Gloves", "1", "essential", "clothing", desc_key="gloves"),

    item("Other shoes (trainers / flip flops)", "1", "recommended", "clothing", desc_key="othershoes"),
    item("Set of clothes for field base / travelling", "1-2", "recommended", "clothing", desc_key="nicerclothes"),
]

DATA = {
    "countries": [
        {"id": "south-africa", "name": "South Africa", "hasCycles": True, "lengths": [10, 7, 5, 4]},
        {"id": "costa-rica", "name": "Costa Rica", "hasCycles": True, "lengths": [10, 7, 5, 4]},
        {"id": "borneo", "name": "Borneo", "hasCycles": True, "lengths": [10, 7, 5, 4]},
        {"id": "legacies", "name": "Legacies", "hasCycles": False, "lengths": ["Legacy Expedition"]},
    ],
    "cycles": [1, 2, 3],
    "items": {
        "south-africa": south_africa,
        "costa-rica": costa_rica,
        "borneo": borneo,
        "legacies": legacies,
    }
}

with open("data.js", "w") as f:
    f.write("// Kit list data - edit this file to add/update items, then push to GitHub to update the live site.\n")
    f.write("// category: 'essential' | 'recommended' | 'optional'\n")
    f.write("// subcategory: 'personal' | 'toiletries' | 'firstaid' | 'clothing'\n")
    f.write("// cycle: 'all' (every cycle) or a number (1, 2, 3) if the item is only needed for one specific cycle - ignored for countries with hasCycles:false\n")
    f.write("// countries[].hasCycles: false means this destination runs once a year with a single fixed kit list - the app skips the cycle step entirely\n")
    f.write("// countries[].lengths: the length options shown for that destination; a single-item list is auto-selected and the length step is skipped\n")
    f.write("const KIT_DATA = ")
    f.write(json.dumps(DATA, indent=2))
    f.write(";\n")

print("Counts:", {k: len(v) for k, v in DATA["items"].items()})
